const snakesQuestions = {
    "level0": {
        "name": "Level 0 - Basics",
        "description": "Phonics Level 0 - Units 1-9",
        "questions": [
            { "question": "Say Hello! What is your name?" },
            { "question": "Say Hello! How are you today?" },
            { "question": "Say Hello! What color is this? (point to something red)" },
            { "question": "Say Hello! What color is this? (point to something blue)" },
            { "question": "Say Hello! Count to 5 for me." },
            { "question": "Say Hello! Count to 10 for me." },
            { "question": "Say Hello! What number comes after 3?" },
            { "question": "Say Hello! What number comes after 7?" },
            { "question": "Say Hello! What is your favorite color?" },
            { "question": "Say Hello! Point to something green in the room." },
            { "question": "Unit 1: What is this?" },
            { "question": "Unit 1: What is this?" },
            { "question": "Unit 1: What is this?" },
            { "question": "Unit 1: What is this?" },
            { "question": "Unit 1: Sit down, please." },
            { "question": "Unit 1: Open your book, please." },
            { "question": "Unit 1: Close your eyes." },
            { "question": "Unit 1: Stand up, please." },
            { "question": "Unit 1: Point to the board." },
            { "question": "Unit 1: Listen carefully." },
            { "question": "Unit 2: What is this? (touch your head)" },
            { "question": "Unit 2: What is this? (touch your nose)" },
            { "question": "Unit 2: What is this? (touch your eye)" },
            { "question": "Unit 2: What is this? (touch your ear)" },
            { "question": "Unit 2: I have two eyes. How many eyes do you see?" },
            { "question": "Unit 2: I have one nose. How many noses?" },
            { "question": "Unit 2: How many fingers do you have?" },
            { "question": "Unit 2: Point to your mouth." },
            { "question": "Unit 2: Show me your hand." },
            { "question": "Unit 2: Touch your hair." },
            { "question": "Unit 3: Who is this? (point to a family photo)" },
            { "question": "Unit 3: Is this your mother?" },
            { "question": "Unit 3: Is this your father?" },
            { "question": "Unit 3: This is my brother. Who is he?" },
            { "question": "Unit 3: This is my sister. Who is she?" },
            { "question": "Unit 3: How many people are in your family?" },
            { "question": "Unit 3: Do you have a pet?" },
            { "question": "Unit 3: What is your mother's name?" },
            { "question": "Unit 3: Do you have a brother or sister?" },
            { "question": "Unit 3: Who is your best friend?" },
            { "question": "Unit 4: What is your favorite animal?" },
            { "question": "Unit 4: What animal says 'meow'?" },
            { "question": "Unit 4: What animal says 'woof'?" },
            { "question": "Unit 4: What animal lives in the water?" },
            { "question": "Unit 4: Is the elephant big or small?" },
            { "question": "Unit 4: Is the mouse big or small?" },
            { "question": "Unit 4: What color is a lion?" },
            { "question": "Unit 4: What color is a panda?" },
            { "question": "Unit 4: Can a fish fly?" },
            { "question": "Unit 4: Can a bird swim?" },
            { "question": "Unit 5: What food do you like?" },
            { "question": "Unit 5: Do you like apples?" },
            { "question": "Unit 5: Do you like pizza?" },
            { "question": "Unit 5: I like ice cream. Do you like it?" },
            { "question": "Unit 5: I don't like broccoli. Do you like it?" },
            { "question": "Unit 5: What is your favorite fruit?" },
            { "question": "Unit 5: What is your favorite food?" },
            { "question": "Unit 5: Do you like milk?" },
            { "question": "Unit 5: What do you eat for breakfast?" },
            { "question": "Unit 5: Are carrots yummy?" },
            { "question": "Unit 6: Where is the school?" },
            { "question": "Unit 6: Is there a park near here?" },
            { "question": "Unit 6: There is a shop. Where is it?" },
            { "question": "Unit 6: There are many houses. Are there trees?" },
            { "question": "Unit 6: Where is your house?" },
            { "question": "Unit 6: What is near your school?" },
            { "question": "Unit 6: Is there a hospital in your town?" },
            { "question": "Unit 6: Where is the supermarket?" },
            { "question": "Unit 6: Can you find the library?" },
            { "question": "Unit 6: What is your favorite place in town?" },
            { "question": "Unit 7: What does your mother do?" },
            { "question": "Unit 7: Is your father a doctor?" },
            { "question": "Unit 7: She is a teacher. Who is she?" },
            { "question": "Unit 7: He is a firefighter. Who is he?" },
            { "question": "Unit 7: What job do you want to be?" },
            { "question": "Unit 7: Is a teacher a job?" },
            { "question": "Unit 7: Do doctors help people?" },
            { "question": "Unit 7: What does a farmer do?" },
            { "question": "Unit 7: Is the chef in the kitchen?" },
            { "question": "Unit 7: What does a pilot do?" },
            { "question": "Unit 8: What are you wearing today?" },
            { "question": "Unit 8: Are you wearing a shirt?" },
            { "question": "Unit 8: What color is your dress?" },
            { "question": "Unit 8: He is wearing a blue coat. What is he wearing?" },
            { "question": "Unit 8: She is wearing a red skirt. What is she wearing?" },
            { "question": "Unit 8: Are your shoes black or white?" },
            { "question": "Unit 8: Point to your socks." },
            { "question": "Unit 8: What hat are you wearing?" },
            { "question": "Unit 8: Is your jacket warm?" },
            { "question": "Unit 8: What clothes do you wear in summer?" },
            { "question": "Unit 9: What are you doing now?" },
            { "question": "Unit 9: Are you sitting or standing?" },
            { "question": "Unit 9: I am reading. What am I doing?" },
            { "question": "Unit 9: She is writing. What is she doing?" },
            { "question": "Unit 9: Are you eating lunch?" },
            { "question": "Unit 9: What are you drawing?" },
            { "question": "Unit 9: He is running. What is he doing?" },
            { "question": "Unit 9: Are you playing a game?" },
            { "question": "Unit 9: What hobby do you like?" },
            { "question": "Unit 9: Do you like to draw or to sing?" }
        ]
    },
    "level1": {
        "name": "Level 1 - Words",
        "description": "Phonics Level 1 - Units 1-9",
        "questions": [
            { "question": "Friends: What is your name?" },
            { "question": "Friends: How old are you?" },
            { "question": "Friends: What color is your favorite?" },
            { "question": "Friends: My name is Tom. What is my name?" },
            { "question": "Friends: I am 7 years old. How old am I?" },
            { "question": "Friends: What is your friend's name?" },
            { "question": "Friends: Nice to meet you. Say it back." },
            { "question": "Friends: How are you? (Answer with I'm fine)" },
            { "question": "Friends: What is your mother's name?" },
            { "question": "Friends: Do you have a best friend?" },
            { "question": "Unit 1: What is this? (point to a pencil case)" },
            { "question": "Unit 1: Is it a pencil?" },
            { "question": "Unit 1: Yes, it is. Is this a ruler?" },
            { "question": "Unit 1: No, it isn't. What is it?" },
            { "question": "Unit 1: Close the door, please." },
            { "question": "Unit 1: Open the window, please." },
            { "question": "Unit 1: Don't talk. Listen!" },
            { "question": "Unit 1: Pick up your book." },
            { "question": "Unit 1: Put the pencil on the desk." },
            { "question": "Unit 1: What is that? (point to something far)" },
            { "question": "Unit 2: What is his name?" },
            { "question": "Unit 2: What is her name?" },
            { "question": "Unit 2: How old is he?" },
            { "question": "Unit 2: How old is she?" },
            { "question": "Unit 2: He has brown hair. What color is his hair?" },
            { "question": "Unit 2: She has long hair. Is her hair short?" },
            { "question": "Unit 2: The cat is under the table. Where is it?" },
            { "question": "Unit 2: The ball is on the chair. Where is it?" },
            { "question": "Unit 2: What is the dog's name?" },
            { "question": "Unit 2: Is the dog big or small?" },
            { "question": "Unit 3: Where is the cat? (in, on, under)" },
            { "question": "Unit 3: The book is in the bag. Where is it?" },
            { "question": "Unit 3: I like dogs. Do you like dogs?" },
            { "question": "Unit 3: I don't like spiders. Do you like them?" },
            { "question": "Unit 3: What animal is in the box?" },
            { "question": "Unit 3: The toy is under the bed. Where is it?" },
            { "question": "Unit 3: Is the cat on the mat?" },
            { "question": "Unit 3: I like cats. What animal do you like?" },
            { "question": "Unit 3: Point to something you like." },
            { "question": "Unit 3: Do you like the red toy or the blue toy?" },
            { "question": "Unit 4: I have a pencil. Do you have one?" },
            { "question": "Unit 4: I don't have a ruler. Do you have one?" },
            { "question": "Unit 4: Do you have any brothers?" },
            { "question": "Unit 4: How many pencils do you have?" },
            { "question": "Unit 4: She has long hair. What does she have?" },
            { "question": "Unit 4: He has blue eyes. What does he have?" },
            { "question": "Unit 4: Do you have a pet?" },
            { "question": "Unit 4: I don't have a sister. Do you have one?" },
            { "question": "Unit 4: How many books do you have?" },
            { "question": "Unit 4: She has two brothers. How many does she have?" },
            { "question": "Unit 5: What do you do on Sunday?" },
            { "question": "Unit 5: I play soccer on Saturday. What do you do?" },
            { "question": "Unit 5: Do you watch TV every day?" },
            { "question": "Unit 5: She reads books on Mondays. What does she do?" },
            { "question": "Unit 5: He goes to school every day. Does he like it?" },
            { "question": "Unit 5: Yes, I do. Do you like school?" },
            { "question": "Unit 5: No, I don't. Do you like homework?" },
            { "question": "Unit 5: What day is it today?" },
            { "question": "Unit 5: What is your favorite day?" },
            { "question": "Unit 5: I eat lunch at 12 o'clock. When do you eat?" },
            { "question": "Unit 6: There's a cat in the room. Where is it?" },
            { "question": "Unit 6: There are three dogs in the park. How many?" },
            { "question": "Unit 6: Is there a tree near the house?" },
            { "question": "Unit 6: Are there any birds in the sky?" },
            { "question": "Unit 6: How many chairs are in the classroom?" },
            { "question": "Unit 6: There's a book on the table. Where is it?" },
            { "question": "Unit 6: There are some children in the garden. Who is there?" },
            { "question": "Unit 6: Is there a window in this room?" },
            { "question": "Unit 6: How many windows are there?" },
            { "question": "Unit 6: There isn't a TV in my bedroom. Is there one in yours?" },
            { "question": "Unit 7: What did you do yesterday?" },
            { "question": "Unit 7: I played soccer yesterday. What did you play?" },
            { "question": "Unit 7: Did you go to school today?" },
            { "question": "Unit 7: She watched TV last night. What did she do?" },
            { "question": "Unit 7: He ate an apple. What did he eat?" },
            { "question": "Unit 7: Did you watch a cartoon?" },
            { "question": "Unit 7: No, I didn't. Did you watch one?" },
            { "question": "Unit 7: What was for breakfast?" },
            { "question": "Unit 7: Where did you go last weekend?" },
            { "question": "Unit 7: Did you have fun?" },
            { "question": "Unit 8: Where were you yesterday?" },
            { "question": "Unit 8: I was at home. Where were you?" },
            { "question": "Unit 8: Was it raining today?" },
            { "question": "Unit 8: The weather was sunny. Was it cold?" },
            { "question": "Unit 8: Were you happy yesterday?" },
            { "question": "Unit 8: She was in the library. Where was she?" },
            { "question": "Unit 8: They were at the park. Where were they?" },
            { "question": "Unit 8: Was the movie good?" },
            { "question": "Unit 8: Were the children in the class?" },
            { "question": "Unit 8: How was your weekend?" }
        ]
    },
    "level2": {
        "name": "Level 2 - Simple Sentences",
        "description": "Phonics Level 2 - Units 1-9",
        "questions": [
            { "question": "Back to school: There is a new student in class. Who is here?" },
            { "question": "Back to school: There are some books on the desk. What is there?" },
            { "question": "Back to school: Open your textbook to page 10." },
            { "question": "Back to school: Don't forget your homework." },
            { "question": "Back to school: Raise your hand to answer." },
            { "question": "Back to school: There is a pencil on the floor. Pick it up." },
            { "question": "Back to school: There are some crayons in the box. Count them." },
            { "question": "Back to school: Be quiet in the hallway." },
            { "question": "Back to school: There is a map on the wall. What is it?" },
            { "question": "Back to school: Listen carefully to the teacher." },
            { "question": "Unit 1: What time is it? (3:00)" },
            { "question": "Unit 1: She gets up at 7 o'clock every morning. What does she do?" },
            { "question": "Unit 1: He goes to school by bus. How does he get there?" },
            { "question": "Unit 1: My mother makes breakfast every day. What does she do?" },
            { "question": "Unit 1: She eats lunch at noon. When does she eat?" },
            { "question": "Unit 1: The bus arrives at 8 AM. What time is it?" },
            { "question": "Unit 1: He brushes his teeth twice a day. How often does he brush?" },
            { "question": "Unit 1: I go to bed at 9 PM. When do I go to bed?" },
            { "question": "Unit 1: She reads a story before sleep. What does she do?" },
            { "question": "Unit 1: School starts at 8:30. What time does school start?" },
            { "question": "Unit 2: The lion likes meat. Does the lion like vegetables?" },
            { "question": "Unit 2: The monkey does not like bananas. What doesn't it like?" },
            { "question": "Unit 2: Does the elephant like water?" },
            { "question": "Unit 2: Yes, it does. The zebra likes grass. What does it like?" },
            { "question": "Unit 2: No, she doesn't. Does the tiger like meat?" },
            { "question": "Unit 2: The bear likes honey. What does the bear like?" },
            { "question": "Unit 2: They don't like the zoo. Do you like it?" },
            { "question": "Unit 2: My favorite animal is the panda. What is yours?" },
            { "question": "Unit 2: Does the snake like the hot sun?" },
            { "question": "Unit 2: The giraffe doesn't eat meat. What does it eat?" },
            { "question": "Unit 3: Where do you live?" },
            { "question": "Unit 3: She has a big house. What does she have?" },
            { "question": "Unit 3: He has a dog. Does he have a cat?" },
            { "question": "Unit 3: The house is next to the park. Where is it?" },
            { "question": "Unit 3: The cat is in front of the tree. Where is it?" },
            { "question": "Unit 3: I live in an apartment. Where do you live?" },
            { "question": "Unit 3: There is a school behind my house. Where is the school?" },
            { "question": "Unit 3: Do you have a bedroom on the second floor?" },
            { "question": "Unit 3: The store is across from the library. Where is it?" },
            { "question": "Unit 3: We live near the beach. Where do we live?" },
            { "question": "Unit 4: Would you like an apple?" },
            { "question": "Unit 4: Is there any milk in the refrigerator?" },
            { "question": "Unit 4: Are there any oranges in the basket?" },
            { "question": "Unit 4: I would like some water, please." },
            { "question": "Unit 4: There isn't any bread. Is there any cheese?" },
            { "question": "Unit 4: Would you like a sandwich or a salad?" },
            { "question": "Unit 4: There are some cookies on the table. Are there enough?" },
            { "question": "Unit 4: I'd like a piece of cake. What would you like?" },
            { "question": "Unit 4: Is there any juice, or do you want water?" },
            { "question": "Unit 4: Are there any vegetables you don't like?" },
            { "question": "Unit 5: This is my bed. What is this?" },
            { "question": "Unit 5: That is your desk. What is that?" },
            { "question": "Unit 5: These are my books. What are these?" },
            { "question": "Unit 5: Those are his toys. Whose toys are those?" },
            { "question": "Unit 5: Whose ball is this?" },
            { "question": "Unit 5: This is my room. Whose room is it?" },
            { "question": "Unit 5: These clothes are clean. Are those dirty?" },
            { "question": "Unit 5: That window is open. Is this one open too?" },
            { "question": "Unit 5: These shoes are too small. What about those?" },
            { "question": "Unit 5: Whose pencil is on the desk?" },
            { "question": "Unit 6: Are you happy today?" },
            { "question": "Unit 6: He is tall. Is she tall too?" },
            { "question": "Unit 6: Our teacher is kind. What is she like?" },
            { "question": "Unit 6: Their house is big. How is their house?" },
            { "question": "Unit 6: What month is your birthday?" },
            { "question": "Unit 6: December is a cold month. What is it like?" },
            { "question": "Unit 6: I am excited about the trip. How do you feel?" },
            { "question": "Unit 6: My friends are ready. Are yours ready?" },
            { "question": "Unit 6: July is hot. Is January cold?" },
            { "question": "Unit 6: We are hungry. Are you hungry too?" },
            { "question": "Unit 7: I'd like to play a game. What would you like to do?" },
            { "question": "Unit 7: I'd like to go outside. Where would you like to go?" },
            { "question": "Unit 7: Do you like swimming?" },
            { "question": "Unit 7: He enjoys reading. What does he enjoy doing?" },
            { "question": "Unit 7: I am thinking about the answer. What are you thinking about?" },
            { "question": "Unit 7: Would you like to draw a picture?" },
            { "question": "Unit 7: She likes singing. Does she like dancing?" },
            { "question": "Unit 7: I want to learn English. What do you want to learn?" },
            { "question": "Unit 7: He's trying to understand. What is he trying to do?" },
            { "question": "Unit 7: Would you like to help me?" },
            { "question": "Unit 8: I like playing soccer. What do you like doing?" },
            { "question": "Unit 8: She enjoys swimming. What does she enjoy?" },
            { "question": "Unit 8: He likes basketball. Does he like baseball?" },
            { "question": "Unit 8: I am good at running. What are you good at?" },
            { "question": "Unit 8: Do you like playing video games?" },
            { "question": "Unit 8: They love dancing. What do they love doing?" },
            { "question": "Unit 8: My hobby is collecting stamps. What is your hobby?" },
            { "question": "Unit 8: He hates losing. Does he like winning?" },
            { "question": "Unit 8: I practice guitar every day. What do you practice?" },
            { "question": "Unit 8: Do you enjoy reading books?" },
            { "question": "Unit 9: Can you swim?" },
            { "question": "Unit 9: Can I have some water, please?" },
            { "question": "Unit 9: She can ride a bike. What can she do?" },
            { "question": "Unit 9: Can you speak English?" },
            { "question": "Unit 9: He can't come to the party. What can't he do?" },
            { "question": "Unit 9: Can I help you with that?" },
            { "question": "Unit 9: They can speak two languages. How many can they speak?" },
            { "question": "Unit 9: Can you draw a circle?" },
            { "question": "Unit 9: I can't find my shoes. What can't you find?" },
            { "question": "Unit 9: Can she dance well?" }
        ]
    },
    "level3": {
        "name": "Level 3 - Intermediate",
        "description": "More complex sentence structures",
        "questions": [
            { "question": "If it rains, I ___ my umbrella." },
            { "question": "She ___ to the store yesterday." },
            { "question": "They ___ their homework yet." },
            { "question": "I wish I ___ more money." },
            { "question": "He told me ___ the door." },
            { "question": "The book ___ interesting is on the shelf." },
            { "question": "She is the ___ student in the class." },
            { "question": "If I ___ rich, I would travel." },
            { "question": "He insisted that she ___ on time." },
            { "question": "The movie was ___ than the book." }
        ]
    },
    "level4": {
        "name": "Level 4 - Advanced",
        "description": "Advanced grammar and vocabulary",
        "questions": [
            { "question": "Despite ___ hard, he failed." },
            { "question": "I would rather ___ than stay." },
            { "question": "It is essential that he ___ on time." },
            { "question": "The manager insisted that the report ___ immediately." },
            { "question": "She acts as if she ___ the owner." },
            { "question": "I regret ___ that to him." },
            { "question": "His behavior is ___ annoying." },
            { "question": "She has a strong ___ for music." },
            { "question": "The politician made a ___ statement." },
            { "question": "His explanation was completely ___." }
        ]
    },
    "level5": {
        "name": "Level 5 - Expert",
        "description": "Complex topics and abstract concepts",
        "questions": [
            { "question": "What does 'ubiquitous' mean?" },
            { "question": "What does 'ephemeral' mean?" },
            { "question": "What does 'paradigm' mean?" },
            { "question": "What does 'pragmatic' mean?" },
            { "question": "What does 'ambiguous' mean?" },
            { "question": "What does 'mitigate' mean?" },
            { "question": "What does 'proliferate' mean?" },
            { "question": "What does 'scrutinize' mean?" },
            { "question": "What does 'ostentatious' mean?" },
            { "question": "What does 'enigma' mean?" }
        ]
    },
    "level6": {
        "name": "Level 6 - Discussion",
        "description": "Open-ended discussion questions",
        "questions": [
            { "question": "What would you do if you had a lot of money?" },
            { "question": "What food have you never eaten?" },
            { "question": "What does 'rambunctious' mean?" },
            { "question": "If you could travel anywhere, where would you go?" },
            { "question": "What is your biggest fear?" },
            { "question": "If you could meet anyone, who would it be?" },
            { "question": "What is the best advice you've ever received?" },
            { "question": "If you could change one thing about the world, what would it be?" },
            { "question": "What skill would you like to learn?" },
            { "question": "What is your favorite childhood memory?" }
        ]
    }
};

const SNAKES_LADDERS_CONFIG = {
    "gridSizes": [
        { "size": 6, "name": "6×6 - Small" },
        { "size": 8, "name": "8×8 - Medium" },
        { "size": 10, "name": "10×10 - Large" }
    ],
    "difficultyLevels": [
        { "level": 0, "name": "Level 0 - Basics" },
        { "level": 1, "name": "Level 1 - Words" },
        { "level": 2, "name": "Level 2 - Simple Sentences" },
        { "level": 3, "name": "Level 3 - Intermediate" },
        { "level": 4, "name": "Level 4 - Advanced" },
        { "level": 5, "name": "Level 5 - Expert" },
        { "level": 6, "name": "Level 6 - Discussion" }
    ],
    "playerTokens": [
        { "id": "token1", "emoji": "🔴", "name": "Red Circle" },
        { "id": "token2", "emoji": "🔵", "name": "Blue Circle" },
        { "id": "token3", "emoji": "🟢", "name": "Green Circle" },
        { "id": "token4", "emoji": "🟡", "name": "Yellow Circle" },
        { "id": "token5", "emoji": "🐱", "name": "Cat" },
        { "id": "token6", "emoji": "🐶", "name": "Dog" },
        { "id": "token7", "emoji": "🐰", "name": "Rabbit" },
        { "id": "token8", "emoji": "🐸", "name": "Frog" },
        { "id": "token9", "emoji": "🦁", "name": "Lion" },
        { "id": "token10", "emoji": "🦄", "name": "Unicorn" },
        { "id": "token11", "emoji": "🚗", "name": "Car" },
        { "id": "token12", "emoji": "🚀", "name": "Rocket" }
    ],
    "defaultSnakes": [
        { "start": 99, "end": 54 },
        { "start": 70, "end": 55 },
        { "start": 52, "end": 29 },
        { "start": 25, "end": 6 },
        { "start": 95, "end": 72 }
    ],
    "defaultLadders": [
        { "start": 3, "end": 22 },
        { "start": 8, "end": 31 },
        { "start": 15, "end": 44 },
        { "start": 28, "end": 56 },
        { "start": 36, "end": 57 },
        { "start": 63, "end": 86 },
        { "start": 68, "end": 92 }
    ]
};